# Generated by Django 5.1.7 on 2025-03-25 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('alto', models.IntegerField()),
                ('ancho', models.IntegerField()),
                ('fondo', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion_tipo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('descripcion_imagen', models.CharField(blank=True, max_length=200)),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventarioApp.mueble')),
            ],
        ),
        migrations.AddField(
            model_name='mueble',
            name='tipo_mueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarioApp.tipomueble'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasillo', models.CharField(max_length=45)),
                ('columna', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['pasillo', 'columna', 'nivel'],
                'unique_together': {('pasillo', 'columna', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.mueble')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarioApp.ubicacion')),
            ],
        ),
    ]
